# Copyright (C) 2026 Bathur.
# Licensed under GPL-3.0-only with the Rider/ReSharper host linking permission.
# See LICENSE and LICENSING.md in the public source root.

DotnetPluginId=ReSharperMcpToolset
DotnetAssemblyName=Bathur.ReSharperMcpToolset
DotnetSolution=ReSharperMcpToolset.sln
RiderPluginId=local.bathur.resharper.mcp.toolset
PluginVersion=0.3.6
BuildConfiguration=Release

RiderBuild=262.9437.287

kotlin.stdlib.default.dependency=false
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.jetbrains.intellij.platform.downloadSources=false
org.jetbrains.intellij.platform.intellijPlatformCache=.intellijPlatform
org.jetbrains.intellij.platform.verifyPluginDefaultRecommendedIdes=false
org.gradle.java.installations.auto-detect=false
